export { backgrounds } from './backgrounds'
export { borders } from './borders'
export { buttons } from './buttons'
export { dims } from './dims'
export { pallete } from './pallete'
export { shadows } from './shadows'
export { texts } from './texts'
